# Configuración principal de Nginx
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Compresión Gzip
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 256;

    server {
        listen 80;
        server_name localhost;

        # === FRONTEND ===
        root /usr/share/nginx/html;
        index index.html;

        # SPA: Angular, React, Astro
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Logs
        access_log /var/log/nginx/access.log;
    }
}
